### ISSUE TITLE
GraphQLError [Object]: Unsupported core schema feature and/or version: [object Object]

### ISSUE THREAD

**Issue by deekshasharma** [apollographql/federation#1249]
Hi, 
I am running the Apollo Federation example available at [https://www.apollographql.com/docs/federation/quickstart/](https://www.apollographql.com/docs/federation/quickstart/) and I am getting the error below when running `node index.js`. Can someone point out what's going on? Am I missing something?

```
GraphQLError [Object]: Unsupported core schema feature and/or version: [object Object]
    at Object.buildComposedSchema (/Users/deekshasharma/Desktop/deeksha-github/apollo-federation/node_modules/@apollo/query-planner/dist/composedSchema/buildComposedSchema.js:26:19)
    at ApolloGateway.createSchemaFromSupergraphSdl (/Users/deekshasharma/Desktop/deeksha-github/apollo-federation/node_modules/@apollo/gateway/dist/index.js:509:40)
    at ApolloGateway.loadStatic (/Users/deekshasharma/Desktop/deeksha-github/apollo-federation/node_modules/@apollo/gateway/dist/index.js:282:24)
    at ApolloGateway.load (/Users/deekshasharma/Desktop/deeksha-github/apollo-federation/node_modules/@apollo/gateway/dist/index.js:265:20)
    at SchemaManager.start (/Users/deekshasharma/Desktop/deeksha-github/apollo-federation/node_modules/apollo-server-core/dist/utils/schemaManager.js:42:65)
    at ApolloServer._start (/Users/deekshasharma/Desktop/deeksha-github/apollo-federation/node_modules/apollo-server-core/dist/ApolloServer.js:146:50)
    at ApolloServer.listen (/Users/deekshasharma/Desktop/deeksha-github/apollo-federation/node_modules/apollo-server/dist/index.js:67:20)
    at Object.<anonymous> (/Users/deekshasharma/Desktop/deeksha-github/apollo-federation/index.js:15:8)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  locations: [ { line: 1, column: 1 } ]
```

- My Node version is `v14.18.1`
- And below are the contents of my `package.json`
```
{
  "name": "apollo-federation",
  "version": "1.0.0",
  "description": "An example to create supergraph using Apollo Federation 2 subgraphs",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@apollo/gateway": "^0.38.2",
    "apollo-server": "^3.5.0",
    "graphql": "^15.7.2"
  }
}

```

**Comment by trevor-scheer** [comment]
Hey @deekshasharma, sorry for the trouble with this. Can you share the project with me as a repo that I can clone? The package file is really only helpful up to a point.

Also I see in the description of your package file you mention Fed 2, but your gateway version is in the `0.x` range which doesn't support that. I think you're looking for `@apollo/gateway@2.0.0-alpha.1`. It would also be helpful to know what version of `rover` you're using.

**Comment by deekshasharma** [comment]
@trevor-scheer Yes that was the issue. 
I installed `@apollo/gateway@2.0.0-alpha.1` instead of `@apollo/gateway` and I am able to get my server up and running. But the documentation [here](https://www.apollographql.com/docs/federation/quickstart/) needs to address that. It asks users to install `@apollo/gateway`.
Is  `@apollo/gateway` production ready ? I am thinking of using Apollo Federation in production and looking for a stable version that could be used.

**Comment by trevor-scheer** [comment]
Glad that got you to the next step. Many folks have been using Fed 1 in production for over 2 years now, but Fed 2 is still considered alpha and is only recommended for experimentation for now. The Fed 2 team is working hard at ensuring a seamless transition from 1 to 2. Given that, my suggestion would be to stick to Fed 1 for your production needs and get up to speed with Fed 2 to prepare for when it's considered production ready. In the meantime, Fed 1 is still being maintained and will be through the transition to Fed 2.

The link you sent is to Fed 1 documentation, so I don't think it should be updated to suggest installing the Fed 2 alpha versions of anything. However, if that issue exists using strictly Fed 1 versions of everything (including `rover`) then I would agree that that's something we ought to resolve.

Note the version switcher in the docs:
![image](https://user-images.githubusercontent.com/29644393/143905634-e2193901-cac5-4626-bee5-eadd32663c53.png)

Also be warned that the Fed 2 docs are currently a WIP, so you may encounter issues or outdated information if you're working through them.

**Comment by PreetamSing** [comment]
I don't know why but running `npm i @apollo/gateway` installs `0.38.2`, version which causes this issue.
The latest stable version of `@apollo/gateway` is `0.44.1`
You can see that here in the [package.json](https://github.com/apollographql/federation/blob/version-0.x/gateway-js/package.json#L3)
I ran into the exact same issue. Running `npm i @apollo/gateway@0.44.1` solved it for me, and also upgrading to alpha version too solved it.

**Comment by trevor-scheer** [comment]
Ah, thanks for letting me know. Looks like I misplaced the `latest` tag in a recent backport release. Should be fixed now!
