### ISSUE TITLE
Runtime error while invoking `composition/validate` while constructing a subgraph

### ISSUE THREAD

**Issue by drazenbuljovcic** [apollographql/federation#1272]
Hello, we are encountering an issue while using the library, during build time, the library is bundled into our output code and this code is run on the **server**.
Can you point me to the right method/direction from where this error might get thrown, as currently we have access only to the `dist` code of the library, in order to help us debug we need assistance seeing the responsible code in the source code, please?
In this case the error is pretty severe, not caught, and so the error message is not helpful at all!

**Expected behaviour**
The application shouldn't crash while running code with `@appolo/foundation`.

---

instalation: **yarn**
bundled through: **webpack**

**node version**: v14.17.1

**Dependencies**
"@apollo/client": "3.4.17",
"@apollo/federation": "0.33.7",
"@apollo/gateway": "0.42.3",

```
<buildPath>/lib/server.js:15227
/**/ 			throw e;
         			^

TypeError: Cannot read property 'map' of undefined
    at Object.<anonymous> (<project>/node_modules/@apollo/federation/dist/composition/validate/preNormalization/tagDirective.js:10:66)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (<project>/node_modules/@apollo/federation/dist/composition/validate/preNormalization/index.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (<project>/node_modules/@apollo/federation/dist/composition/validate/index.js:24:44)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
[nodemon] app crashed - waiting for file changes before starting...
```

Thank you so much for your help! 🙏

**Comment by trevor-scheer** [comment]
The clue is here at the top of the stack:
```
TypeError: Cannot read property 'map' of undefined
    at Object.<anonymous> (<project>/node_modules/@apollo/federation/dist/composition/validate/preNormalization/tagDirective.js:10:66)
```
I can navigate to that file and line number and see there's an array being mapped (which is undefined in your case for some reason). That array is coming from the `@apollo/subgraph` package. Can you see if your project has that installed? It's a dependency of `@apollo/federation`. The `npm ls @apollo/subgraph` command should be helpful.

This is about the best help I can provide without a reproduction that I can run on my machine. I'm going to close this, but happy to reopen with a reproduction.

Side note: there's rarely a reason to install the `@apollo/federation` package into your project anymore (it's expected that the gateway uses it for now, but you shouldn't need to). If you're running a subgraph, you should be moving to the `buildSubgraphSchema` function exported by the `@apollo/subgraph` package instead.
