### ISSUE TITLE
router-bridge: Do not panic when serializing or deserializing to interact with deno-core

### ISSUE THREAD

**Issue by garypen** [apollographql/federation#1320]
The router-bridge panics if:
 - it cannot serialize a parameter
 - it cannot execute_script() in the deno-core runtime

These kinds of problems are difficult to debug. It would be better if the router bridge could handle the errors and log/propagate problems back to the router.

There is an issue in the router at the moment where structures have changed in the router and deserialization errors lead to a panic. It's simple to reproduce by just running the diagnose-endpoint tool against your router to trigger and introspection query which causes a panic.

e.g.;

```
npx diagnose-endpoint@1.0.12 --endpoint=http://localhost:4000`

thread 'tokio-runtime-worker' panicked at 'unable to invoke var _a;
Object.defineProperty(exports, "__esModule", { value: true });
const planResult = bridge.plan(schemaString, queryString, operationName);
if (((_a = planResult.errors) === null || _a === void 0 ? void 0 : _a.length) > 0) {
    done({ Err: planResult.errors });
}
else {
    done({ Ok: planResult.data });
}
//# sourceMappingURL=do_plan.js.map in JavaScript runtime 
 error: 
 Error: Error parsing args: missing field `node`
    at Object.opSync (deno:core/01_core.js:142:12)
    at done (<init>:7:15)
    at do_plan:8:5', /Users/garypen/.asdf/installs/rust/1.57.0/git/checkouts/federation-320f8bad94ab52a0/e88ce2a/router-bridge/src/js.rs:65:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'unable to invoke var _a;
Object.defineProperty(exports, "__esModule", { value: true });
const planResult = bridge.plan(schemaString, queryString, operationName);
if (((_a = planResult.errors) === null || _a === void 0 ? void 0 : _a.length) > 0) {
    done({ Err: planResult.errors });
}
else {
    done({ Ok: planResult.data });
}
//# sourceMappingURL=do_plan.js.map in JavaScript runtime 
 error: 
 Error: Error parsing args: missing field `node`
    at Object.opSync (deno:core/01_core.js:142:12)
    at done (<init>:7:15)
    at do_plan:8:5', /Users/garypen/.asdf/installs/rust/1.57.0/git/checkouts/federation-320f8bad94ab52a0/e88ce2a/router-bridge/src/js.rs:65:13
```

**Comment by o0Ignition0o** [comment]
Just had a chat with @trevor-scheer and he did confirm that introspection query plans are empty, because there isn't anything to actually fetch downstream.

 PRs incoming :D
