### ISSUE TITLE
[gateway] GraphQLNonNull cannot be invoked without 'new' with Graphql@16.3.0

### ISSUE THREAD

**Issue by gustaff-weldon** [apollographql/federation#1555]
We have upgraded graphql dependency in our gateway project from 15.8.0 to 16.3.0.

Starting gateway mode throws an error:
```
/Users/edit/work/zencargo/monorepo/graphql-gateway/node_modules/@apollo/core-schema/src/schema.ts:199
    feature: { type: GraphQLNonNull(GraphQLString), },
                                   ^
TypeError: Class constructor GraphQLNonNull cannot be invoked without 'new'
    at Object.<anonymous> (/Users/edit/work/zencargo/monorepo/graphql-gateway/node_modules/@apollo/core-schema/src/schema.ts:199:36)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/edit/work/zencargo/monorepo/graphql-gateway/node_modules/@apollo/core-schema/src/index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

We are starting gateway with roughly code below:
```
const createGateway = (config: GatewayConfig): ApolloGateway =>
  new ApolloGateway({
    buildService: ({ url }) => new RemoteGraphQLDataSourceWithContext({ url }),
  });


const gatewayConfig: GatewayConfig =
  apolloStudioKey === ""
    ? { supergraphSdl: new IntrospectAndCompose({ subgraphs: services }) }
    : {};

export const defaultGateway = createGateway(gatewayConfig);
export const defaultServer = new Server(defaultGateway);

const { url } = await server.start({ port });
```

Related dependencies:
```
  "dependencies": {
    "@apollo/federation": "^0.35.1",
    "@apollo/gateway": "^0.48.1",
    "apollo-server": "^3.6.3",
    "apollo-server-core": "^3.6.3",
    "graphql": "^16.3.0",
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^2.6.2",
    "@graphql-codegen/typescript": "^2.4.5",
    "@graphql-codegen/typescript-resolvers": "^2.5.2",
    "apollo-server-types": "^3.5.0",
    "typescript": "^4.5.5"
  },
```

Expected behaviour is to start gateway without issues.
I was checking changelog for gateway and could not find any notes about any Graphql 16 changes

**Comment by 100phel** [comment]
Having the same issue. Did you find any solution?

**Comment by pcmanus** [comment]
@clenfest, @queerviolet: this seems related to the intersection of graph 16 upgrades and the `@apollo/core-schema` lib, could you have a look.
