### ISSUE TITLE
Federation v2 validation error related to @requires directive

### ISSUE THREAD

**Issue by ehardy** [apollographql/federation#2102]
Hello team,

We are migrating our GraphQL infrastructure to Federation v2. It is mostly a smooth ride so far. There's one issue regarding our usage of the `@requires` directive that used to work under Federation v1 that now fails to validate under Federation v2. Not sure if this is a bug or to be expected, at least it's different behaviour. 

The problem is with the `@requires("code product")` directive in the `inventorySchema` below. When composing the federated schema using Federation v2, we are getting the following error:

```shell
[
  GraphQLError: Invalid empty selection set for field "ProductEdition.product" of non-leaf type Product!
      at validate (.../node_modules/@apollo/federation-internals/dist/operations.js:11:15)
      at FieldSelection.validate (.../node_modules/@apollo/federation-internals/dist/operations.js:798:9)
      at SelectionSet.validate (.../node_modules/@apollo/federation-internals/dist/operations.js:613:23)
      at parseSelectionSet (.../node_modules/@apollo/federation-internals/dist/operations.js:1126:22)
      at parseFieldSetArgument (.../node_modules/@apollo/federation-internals/dist/federation.js:755:51)
      at validateFieldSet (.../node_modules/@apollo/federation-internals/dist/federation.js:94:30)
      at validateAllFieldSet (.../node_modules/@apollo/federation-internals/dist/federation.js:149:23)
      at FederationBlueprint.onValidation (.../node_modules/@apollo/federation-internals/dist/federation.js:496:9)
      at .../node_modules/@apollo/federation-internals/dist/definitions.js:1097:41
      at Schema.runWithBuiltInModificationAllowed (.../node_modules/@apollo/federation-internals/dist/definitions.js:826:9) {
    message: '[inventory] On field "ProductEdition.inventory", for @requires(fields: "code product"): Invalid empty selection set for field "ProductEdition.product" of non-leaf type Product!',
    path: undefined,
    locations: [ [Object], [Object] ],
    extensions: { code: 'REQUIRES_INVALID_FIELDS' }
  }
]
```

`Product` is indeed a non-leaf type in our schema. The same schemas validate successfully with Federation v1 as mentioned. So not sure what to make about this, haven't found anything regarding changes to the `@requires` directive under Federation v2.

Is this a use case that should have failed to validate under Federation v1 but somehow passed? Is this a breaking change with Federation v2? Should it still validate successfully under Federation v2? Any guidance would be appreciated.

I'm providing an extract of our schemas, enough to reproduce the problem, along with code.

```javascript
const { composeAndValidate } = require('@apollo/federation');
const { parse } = require('graphql');
const { composeServices } = require('@apollo/composition');

const productSchema = `
type Product @key(fields: "id") {
    id: ID!
    name: String!
    vendorID: ID!
}

type ProductEdition @key(fields: "id") {
    id: ID!
    name: String!
    code: String!
    product: Product!
}

type Query {
    product(id: ID!): Product
    edition(id: ID!): ProductEdition
}
`;

const inventorySchema = `
extend type Product @key(fields: "id") {
    id: ID! @external
}

extend type ProductEdition @key(fields: "id") {
    id: ID! @external    
    code: String! @external
    product: Product! @external
    inventory: Inventory @requires(fields: "code product")
}

type Inventory @key(fields: "id") {  
  id: ID!    
  stock: Int  
  vendorId: ID  
}
`;

const productService = {
    name: 'product',
    typeDefs: parse(productSchema)
};

const inventoryService = {
    name: 'inventory',
    typeDefs: parse(inventorySchema)
};

console.log('attempting composition with Federation v1...');
composeWithFederationV1(productService, inventoryService);

console.log('attempting composition with Federation v2...');
composeWithFederationV2(productService, inventoryService);

function composeWithFederationV1(...services) {
    const { schema, errors } = composeAndValidate(services);

    if (errors) {
        console.log(errors);
        return;
    }

    console.log('composed successfully under Federation v1');
}

function composeWithFederationV2(...services) {
    const { errors } = composeServices(services);

    if (errors) {
        console.error(errors);
        return;
    }

    console.log('composed successfully under Federation v2');
}
```

**Comment by ehardy** [comment]
I think I might have found the answer. Could it be that the example above is one of those [breaking changes](https://www.apollographql.com/docs/federation/federation-2/backward-compatibility/#breaking-changes) that should have resulted in errors in Federation v1 but did not? It looks that way. I believe this example is a case of an [invalid @requires directive](https://www.apollographql.com/docs/federation/federation-2/backward-compatibility/#invalid-requires-directives).

If I modify the `inventorySchema` as follows, all is good under Federation v2:

```graphql
extend type Product @key(fields: "id") {
    id: ID! @external
    vendorId: ID! @external
}

extend type ProductEdition @key(fields: "id") {
    id: ID! @external    
    code: String! @external
    product: Product! @external
    inventory: Inventory @requires(fields: "code product { vendorId }")
}

type Inventory @key(fields: "id") {  
  id: ID!    
  stock: Int  
  vendorId: ID  
}
```

The differences being the added `vendorId: ID! @external` field on the `Product` entity, as well as referencing the leaf field `{ vendorId }` within the the `@requires` directive.
