### ISSUE TITLE
Issue running federation gateway in aws lambda

### ISSUE THREAD

**Issue by surenzeroonelabs** [apollographql/federation#2149]
In an attempt to run `Federation Gateway` in `AWS Lambda`, we wrote following code
```typescript
import { ApolloServer as LambdaServer } from 'apollo-server-lambda';
import { ApolloServerExpressConfig } from 'apollo-server-express'
import { ApolloServer } from 'apollo-server';
import { ApolloGateway } from "@apollo/gateway";

const gateway = new ApolloGateway();

const serverConfig: ApolloServerExpressConfig = {
	gateway,
}

// for lambda
const lambdaServer = new LambdaServer(serverConfig)
export const graphqlHandler = lambdaServer.createHandler()

// for localhost
if (process.env.RUNTIME !== "lambda") {
  // The `listen` method launches a web server.
  const server = new ApolloServer(serverConfig);
  server.listen().then(({ url }) => {
    console.log(`🚀  Server ready at ${url}`);
  });
}
```
This code works fine locally but in `Lambda` it errors with following logs
```
2022-09-21T05:17:14.876Z	a063bd55-8e18-4721-ab5c-8bec65c7d06a	ERROR	UplinkSupergraphManager failed to update supergraph with the following error: An error occurred while fetching your schema from Apollo: Expected signal must be an instanceof AbortSignal
2022-09-21T05:17:14.877Z	a063bd55-8e18-4721-ab5c-8bec65c7d06a	ERROR	An error occurred during Apollo Server startup. All GraphQL requests will now fail. The startup error was: An error occurred while fetching your schema from Apollo: Expected signal must be an instanceof AbortSignal
2022-09-21T05:17:14.877Z	a063bd55-8e18-4721-ab5c-8bec65c7d06a	ERROR	An error occurred during Apollo Server startup. All GraphQL requests will now fail. The startup error was: An error occurred while fetching your schema from Apollo: Expected signal must be an instanceof AbortSignal
2022-09-21T05:17:14.878Z	a063bd55-8e18-4721-ab5c-8bec65c7d06a	ERROR	Invoke Error 	{
    "errorType": "Error",
    "errorMessage": "This data graph is missing a valid configuration. More details may be available in the server logs.",
    "stack": [
        "Error: This data graph is missing a valid configuration. More details may be available in the server logs.",
        "    at ApolloServer2._ensureStarted (/var/task/index.js:56309:21)",
        "    at async ApolloServer2.ensureStarted (/var/task/index.js:56323:9)",
        "    at async Runtime.handler (/var/task/index.js:80044:11)"
    ]
}
```

I made sure the environment variables `APOLLO_KEY` and `APOLLO_GRAPH_REF` are populated with proper values.
Also made sure the lambda can talk to outside world by placing an explicit call to Apollo's Uplink url for GCP and AWS.

**Comment by surenzeroonelabs** [comment]
Fixed it. For lambda we need to pass `fetcher` to `ApolloGateway`. `fetcher` can be `fetch` from `node-fetch`.
