### ISSUE TITLE
Fed 2 @composeDirective + repeatable composition exception

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/federation#2173]
Reproduction: https://stackblitz.com/edit/basic-federation-sjbdop?file=one.js,two.js
Versions: `@apollo/gateway@2.1.3`
Behavior: Adding `repeateable` to a directive definition and composing the directive using `@composeDirective` results in an exception on composition: 

```
TypeError: b.hasOwnProperty is not a function
    at objectEquals (/home/projects/basic-federation-sjbdop/node_modules/@apollo/federation-internals/dist/values.js:94:42)
    at valueEquals (/home/projects/basic-federation-sjbdop/node_modules/@apollo/federation-internals/dist/values.js:68:41)
    at Merger.sameDirectiveApplication (/home/projects/basic-federation-sjbdop/node_modules/@apollo/composition/dist/merging/merge.js:1339:55)
    at eval (/home/projects/basic-federation-sjbdop/node_modules/@apollo/composition/dist/merging/merge.js:1290:53)
    at Array.filter (<anonymous>)
    at eval (/home/projects/basic-federation-sjbdop/node_modules/@apollo/composition/dist/merging/merge.js:1290:35)
    at Array.map (<anonymous>)
    at Merger.mergeAppliedDirective (/home/projects/basic-federation-sjbdop/node_modules/@apollo/composition/dist/merging/merge.js:1290:22)
    at Merger.mergeAllAppliedDirectives (/home/projects/basic-federation-sjbdop/node_modules/@apollo/composition/dist/merging/merge.js:1252:22)
    at Merger.merge (/home/projects/basic-federation-sjbdop/node_modules/@apollo/composition/dist/merging/merge.js:220:14)
```

**Comment by clenfest** [comment]
So interestingly, this doesn't actually have much to do with composing custom directives, but it did allow us to find a bug in our object equality tests. It turns out that when you create an object with:

```typescript 
const a = Object.create(null);
const b = {};

a['foo'] = 'foo';
b['foo'] = 'foo';

b.hasOwnProperty('foo'); // true
a.hasOwnProperty('foo'); // this will throw since hasOwnProperty does not exist when the object was created this way.
```

When we create directive arguments here https://github.com/apollographql/federation/blob/main/internals-js/src/definitions.ts#L3063, we do in the way where the `hasOwnProperty` function will not exist.
