### ISSUE TITLE
Issue with scalar Boolean

### ISSUE THREAD

**Issue by paritosh-08** [apollographql/federation#2211]
### Setup

I am creating a subgraph in javascript using the following dependencies:
```JSON
{
  "dependencies": {
    "apollo-server": "3.8.1",
    "graphql": "16.5.0",
    "graphql-tag": "2.12.6",
    "@apollo/gateway": "2.0.3",
    "@apollo/subgraph": "2.0.4"
  }
}
```
<details>
<summary> See the server code </summary>

```JS
const { ApolloServer, gql } = require('apollo-server');
const { buildSubgraphSchema } = require('@apollo/subgraph');
const { GraphQLError } = require('graphql');

const users = [
  {
    id: 1,
    name: 'Foo'
  }
];

const typeDefs = gql`
  scalar Boolean

  type Query {
    getUserData(id: Int!, admin: Boolean = false): user
  }

  type user {
    id: Int!
    name: String
  }
`;

const resolvers = {
  Query: {
    getUserData(parent, args, context, info) {
      if (args.admin) {
        return users.find((user) => user.id === args.id);
      }
      else {
        throw new GraphQLError('Only allowed for admin', {
          extensions: {
            code: 'UNAUTHENTICATED',
            argumentName: 'admin',
          },
        }); 
      }
    }
  }
}

const server = new ApolloServer({
  schema: buildSubgraphSchema({ typeDefs, resolvers })
});

server.listen(4001).then(({ url }) => {
    console.log(`🚀 Server ready at ${url}`);
});
```

</details>

### Issue

When I define the scalar `Boolean` in the graphql schema and use that as a default value for some field; I get an error saying:
```
Invalid default value (got: false) provided for argument Query.getUserData(admin:) of type Boolean.
```
<details> <summary>See full error message</summary>

```
/bug_repro/node_modules/@apollo/federation-internals/dist/federation.js:1005
                throw addSubgraphToError(e, this.name, error_1.ERRORS.INVALID_GRAPHQL);
                ^

GraphQLError: Invalid default value (got: false) provided for argument Query.getUserData(admin:) of type Boolean.
    at Object.err (/bug_repro/node_modules/@apollo/federation-internals/dist/error.js:11:32)
    at Validator.addError (/bug_repro/node_modules/@apollo/federation-internals/dist/validate.js:98:57)
    at Validator.validateArg (/bug_repro/node_modules/@apollo/federation-internals/dist/validate.js:201:18)
    at Validator.validateObjectOrInterfaceType (/bug_repro/node_modules/@apollo/federation-internals/dist/validate.js:126:22)
    at Validator.validate (/bug_repro/node_modules/@apollo/federation-internals/dist/validate.js:59:26)
    at validateSchema (/bug_repro/node_modules/@apollo/federation-internals/dist/validate.js:11:34)
    at Schema.validate (/bug_repro/node_modules/@apollo/federation-internals/dist/definitions.js:1161:62)
    at Subgraph.validate (/bug_repro/node_modules/@apollo/federation-internals/dist/federation.js:1000:25)
    at buildSubgraph (/bug_repro/node_modules/@apollo/federation-internals/dist/federation.js:704:21)
    at buildSubgraphSchema (/bug_repro/node_modules/@apollo/subgraph/dist/buildSubgraphSchema.js:27:63) {
  message: '[<unnamed>] Invalid default value (got: false) provided for argument Query.getUserData(admin:) of type Boolean.',
  path: undefined,
  locations: undefined,
  extensions: { code: 'INVALID_GRAPHQL' }
```
</details>

I have the following type definition for my schema:
```graphql
scalar Boolean

type Query {
  getUserData(id: Int!, admin: Boolean = false): user
}

type user {
  id: Int!
  name: String
}
```

### Workaround
If we replace the `scalar Boolean` with `scalar String` and use `"true"/"false"` instead of `true/false`, then the error is resolved.

### Expected behavior
Using `Boolean` scalar as default should not raise the above-mentioned error.

### Actual behavior
Using `Boolean` scalar as default raises an error, whereas using `String` doesn't.

### Reproducing the error
[boolean_bug_repro.zip](https://github.com/apollographql/federation/files/9836933/boolean_bug_repro.zip)
:point_up: Download the zip attached here and extract it.
Now run the following commands:

```bash
npm install
node index.js
```

**Comment by pcmanus** [comment]
It's definitively strange that manually declaring `Boolean` that way does not work and we'll fix it, but I'll note that `Boolean` is a built-in, so the simple work-around here is not _not_ declare the `scalar Boolean`, which is unnecessary. If that declaration is removing, the example will work as expected.

**Comment by paritosh-08** [comment]
> Boolean is a built-in, so the simple work-around here is not to declare the scalar Boolean, which is unnecessary. If that declaration is removed, the example will work as expected.

Thanks, I will add that under the workaround section.

> It's definitively strange that manually declaring Boolean that way does not work and we'll fix it.

Thanks for looking into the issue. Also, suppose we have a subgraph that explicitly defines `scalar Boolean` in its schema and uses `true/false` as the default value for some field, and we try adding that in a supergraph, then it throws a similar error:
```
Error: A valid schema couldn't be composed. The following composition errors were found:
        [server] Invalid default value (got: false) provided for argument __Type.enumValues(includeDeprecated:) of type Boolean.
        [server] Invalid default value (got: false) provided for argument __Type.fields(includeDeprecated:) of type Boolean.
```

Please let me know if you want to reproduce this as well.

**Comment by paritosh-08** [comment]
Also, this issue is not specific to `Boolean` scalar. Declaring and using `Int` and `Float` scalars as mentioned in the issue also throw the same error.

**Comment by paritosh-08** [comment]
Also, this issue is not specific to `Boolean` scalar. Declaring and using `Int` and `Float` scalars as mentioned in the issue also throw the same error.

**Comment by darrellwarde** [comment]
I am having somewhat of a similar issue here, when trying to compose my supergraph:

```
error[E029]: Encountered 1 build error while trying to build a supergraph.

Caused by:
    UNKNOWN: [locations] Invalid default value (got: true) provided for argument @key(resolvable:) of type Boolean.
```

However, I am _not_ redefining the `Boolean` scalar in my type definitions, so I don't know what's going on here.
