### ISSUE TITLE
`throw new Error(...)` gobbles up underlying strack traces 

### ISSUE THREAD

**Issue by magicmark** [apollographql/federation#2444]
👋 discovered this when debugging why our supergraph service was failing at startup time. We were seeing the following stack trace:

```
Error: Couldn't load service definitions for "my_service" at http://example.com/graphql: Cannot read properties of undefined (reading 'locals')
    at /code/node_modules/@apollo/gateway/src/supergraphManagers/IntrospectAndCompose/loadServicesFromRemoteEndpoint.ts:77:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at loadServicesFromRemoteEndpoint (/code/node_modules/@apollo/gateway/src/supergraphManagers/IntrospectAndCompose/loadServicesFromRemoteEndpoint.ts:81:30)
    at IntrospectAndCompose.updateSupergraphSdl (/code/node_modules/@apollo/gateway/src/supergraphManagers/IntrospectAndCompose/index.ts:92:20)
    at IntrospectAndCompose.initialize (/code/node_modules/@apollo/gateway/src/supergraphManagers/IntrospectAndCompose/index.ts:62:30)
    at ApolloGateway.initializeSupergraphManager (/code/node_modules/@apollo/gateway/src/index.ts:390:22)
    at ApolloGateway.load (/code/node_modules/@apollo/gateway/src/index.ts:300:7)
    at SchemaManager.start (/code/node_modules/@apollo/server/src/utils/schemaManager.ts:108:22)
    at ApolloServer._start (/code/node_modules/@apollo/server/src/ApolloServer.ts:391:24)
```

Note that this stack trace doesn't include any userland lines from where the underlying error was thrown from.

This is thrown from https://github.com/apollographql/federation/blob/112ae8cc5e6cb80ba10ffcc4068a0764c82f1bf6/gateway-js/src/supergraphManagers/IntrospectAndCompose/loadServicesFromRemoteEndpoint.ts#LL77.

Even though we include the `err.message`(s), this doesn't include the rest of the stack trace, so it's difficult to debug without entering into a debugger and pausing on all thrown errors.

Highly relevant https://programming.protips.wiki/chain-errors/

(Although since we're potentially chaining multiple errors, that makes things a little harder, but we can probably still do something here)

Thanks!

**Comment by trevor-scheer** [comment]
Thanks for taking the time to report @magicmark, I think you make great points and sorry for the trouble this caused you for debugging. I can't promise any timeline or prioritization for this but I'd definitely welcome a PR if you (or anyone else) were interested in fixing this.
