### ISSUE TITLE
Union federation fails when __typename is in query

### ISSUE THREAD

**Issue by TheAschr** [apollographql/federation#254]
**Demo repository**: https://github.com/TheAschr/federation-bug-demo

I have a specific situation where federation of a union fails. here is my query:

```gql
{
  accounts {
    id
    user {
      ... on StandardUser {
        id
        film {
          id
          __typename
        }
      }
      ... on AdminUser {
        id
        film {
          id
          review {
            id
          }
        }
      }
    }
  }
}
```

Here is the response I get:

```gql
{
  "errors": [
    {
      "message": "Field \"reviewId\" was not found in response.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Field \"reviewId\" was not found in response.",
            "    at executeSelectionSet (C:\\Users\\me\\Documents\\github\\federation-demo\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:217:27)",
            "    at executeSelectionSet (C:\\Users\\me\\Documents\\github\\federation-demo\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:236:51)",
            "    at C:\\Users\\me\\Documents\\github\\federation-demo\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:121:36",
            "    at Array.forEach (<anonymous>)",
            "    at executeFetch (C:\\Users\\me\\Documents\\github\\federation-demo\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:120:18)",
            "    at executeNode (C:\\Users\\me\\Documents\\github\\federation-demo\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:82:23)",
            "    at executeNode (C:\\Users\\me\\Documents\\github\\federation-demo\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:73:33)",
            "    at executeNode (C:\\Users\\me\\Documents\\github\\federation-demo\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:56:46)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
            "    at async Object.executeQueryPlan (C:\\Users\\me\\Documents\\github\\federation-demo\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:22:27)",
            "    at async Object.ApolloGateway.executor (C:\\Users\\me\\Documents\\github\\federation-demo\\node_modules\\@apollo\\gateway\\dist\\index.js:109:30)"
          ]
        }
      }
    }
  ],
  "data": {
    "accounts": [
      {
        "id": "1",
        "user": {
          "id": "1",
          "film": {
            "id": "1",
            "review": null
          }
        }
      },
      {
        "id": "2",
        "user": {
          "id": "2",
          "film": {
            "id": "1",
            "__typename": "Film"
          }
        }
      }
    ]
  }
}
```

I believe it must be a bug because when I remove __typename the query completes:

```gql
{
  accounts {
    id
    user {
      ... on StandardUser {
        id
        film {
          id
        }
      }
      ... on AdminUser {
        id
        film {
          id
          review {
            id
          }
        }
      }
    }
  }
}
```

**Comment by jtomaszewski** [comment]
I think we met similar issue:

```
# fruits-service
type Banana @key(fields: "id") {
  id: String!
  bananaId: String!
}
type Apple @key(fields: "id") {
  id: String!
  appleId: String!
}

# users-service
extend type Banana @key(fields: "id") {
  id: String! @external
}
extend type Apple @key(fields: "id") {
  id: String! @external
}

type FavouriteFruit = union Banana | Apple

type User {
  favouriteFruit: FavouriteFruit!
}

type Query {
  user: User!
}

# client
query {
  user {
    favouriteFruit {
      id
      ... on Banana {
        bananaId
      }
    }
  }
}
```

Gateway should only ask users-service for `user.favouriteFruit.id`, and then fruits-service for Banana's `bananaId`.

Currently it asks users-service for both, and so users-service fails with "`bananaId` field doesnt exist on `Banana` type".

Which basically means, if you have a union, federation will fail to federate fields of union members (& their nested types?).

Which is a pity! We love union types, now we're not sure how we should handle it.

**Comment by jtomaszewski** [comment]
We had a similar problem, but `__typename` was not the problem. The problem was: union member types would use a different property for `@key` directive.

For example:

`
type A @key(fields: "id") {
  id: ID!
}
type B @key(fields: "id") {
  id: ID!
}
type C @key(fields: "arn") {
  arn: ARN!
}

union AB = A | B
union AC = A | C
```

Federating fields for union `AB` would work, but for `AC` it wouldn't. We had to change the type so that it would use the same field name in the `@key` directive :/ But at least it resolved the "union fields can't be federated" issue for us.
