### ISSUE TITLE
buildPlan TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by NikolaievSerhii** [apollographql/federation#2636]
### Issue Description

I'm trying to make a gateway service using lib version 2.4.8
**versions from package.json**:
```
    "@apollo/server": "^4.7.3",
    "@apollo/server-plugin-landing-page-graphql-playground": "^4.0.1",
    "@apollo/client": "^3.7.15",
    "@apollo/gateway": "^2.4.8",
    "@apollo/composition": "^2.4.8",
    "@apollo/subgraph": "^2.4.8",
```
**Pseudocode snippet** :
```
const app = express();
apolloGateway = new ApolloGateway({
    supergraphSdl: supergraph, // builded using rover cli
 });
apolloServer =  new ApolloServer({
    gateway: apolloGateway,
    introspection: true,
    includeStacktraceInErrorResponses: process.env.NODE_ENV !== "production",
    plugins: [
      process.env.PLAYGROUND === "enabled"
        ? ApolloServerPluginLandingPageGraphQLPlayground()
        : ApolloServerPluginLandingPageDisabled(),
    ],
  });
  
  const monitorServer = app.listen(8081, () => {
    logger({
      action: "apiMetricsStarted",
      message: "🚀 API Metrics ready at http://localhost:8081/metrics",
    });
  });

  await apolloServer.start();

  app.use(
      cors(),
      bodyParser.json(),
      expressMiddleware(apolloServer, {
        context: createContext,
      })
  );

  const server = app.listen(8080, () => {
    logger({
      action: "apiGatewayRunning",
      message: "🚀 API Gateway ready at http://localhost:8080",
    });
  });
```
**supergraph-config.yml** :
```
federation_version: =2.3.2
subgraphs:
  test_service:
    routing_url: http://localhost:8090/graphql
    schema:
      file: ../schemas/service.graphql
```
**service.graphql**:
```
type Query {
    test: Boolean
}
```

Service started successfully, but once I query service via postman:
```
query Test {
    test
}
```
I get error:
```
{
  "code": "INTERNAL_SERVER_ERROR",
  "stacktrace": [
    "TypeError: Cannot read property 'kind' of undefined",
    "    at GroupPath.updatedResponsePath (/Users/username/projectDir/gateway-service/node_modules/@apollo/query-planner/dist/buildPlan.js:971:55)",
    "    at GroupPath.add (/Users/username/projectDir/gateway-service/node_modules/@apollo/query-planner/dist/buildPlan.js:982:100)",
    "    at computeGroupsForTree (/Users/username/projectDir/gateway-service/node_modules/@apollo/query-planner/dist/buildPlan.js:2313:53)",
    "    at computeRootFetchGroups (/Users/username/projectDir/gateway-service/node_modules/@apollo/query-planner/dist/buildPlan.js:2115:9)",
    "    at QueryPlanningTraversal.updatedDependencyGraph (/Users/username/projectDir/gateway-service/node_modules/@apollo/query-planner/dist/buildPlan.js:356:15)",
    "    at QueryPlanningTraversal.computeBestPlanFromClosedBranches (/Users/username/projectDir/gateway-service/node_modules/@apollo/query-planner/dist/buildPlan.js:312:43)",
    "    at QueryPlanningTraversal.findBestPlan (/Users/username/projectDir/gateway-service/node_modules/@apollo/query-planner/dist/buildPlan.js:135:14)",
    "    at computeRootParallelBestPlan (/Users/username/projectDir/gateway-service/node_modules/@apollo/query-planner/dist/buildPlan.js:1935:36)",
    "    at computeRootParallelDependencyGraph (/Users/username/projectDir/gateway-service/node_modules/@apollo/query-planner/dist/buildPlan.js:1927:12)",
    "    at computePlanInternal (/Users/username/projectDir/gateway-service/node_modules/@apollo/query-planner/dist/buildPlan.js:1864:33)"
  ]
}
```
What I've found, that `federation_internals.isNamedType` returns `false` even if type passed to it is `ScalarType` which is subtype of `BaseNamedType`.
Do you have any thoughts on what I configure wrong, or how to fix it?

### Link to Reproduction

-

**Comment by trevor-scheer** [comment]
Can you try bumping the federation in your supergraph config?
`federation_version: =2.3.2` to `federation_version: =2.4.8`

The federation packages are published in lockstep, so that should always match your gateway version.

**Comment by NikolaievSerhii** [comment]
Same error appears

**Comment by nikolaievs** [comment]
Here is link to repo: https://github.com/nikolaievs/apollo-gateway-issue-buildplan
Did not clean `package.json` cuz we're using dependencies in real project

**Comment by trevor-scheer** [comment]
This is missing a `tsconfig.json`. If you can provide all the steps to reproduce the error that would be helpful as well.

**Comment by nikolaievs** [comment]
Added file.
Steps:
 - Run gateway: `npm run build && node build/index.js`
 - Send request via Postman

**Comment by trevor-scheer** [comment]
Blows up on my machine with this error. Tried with both npm and yarn, node 18 and 20. Not sure why a `SyntaxError` would be thrown on optional chain. Can you simplify the reproduction?
```
/Users/trevorscheer/Desktop/repro/apollo-gateway-issue-buildplan/node_modules/path-scurry/node_modules/lru-cache/dist/cjs/index.js:52
            this.signal.onabort?.(reason);
                                ^

SyntaxError: Invalid or unexpected token
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)

Node.js v20.4.0
```

**Comment by nikolaievs** [comment]
Oh, yeah. Sorry, actually this is one more issue that I faced building gateway, but I'd managed to fix it by editing `node_modules`: replace all `?.` calls just with `.` Also, as I can see this `lru-cache` is your sub dependency from `@apollo/server`.
So as a result I was able to run the service and try to test, but it failed because of `_kind_ of undefined` problem .
Also, I've tried node 14 and 16.

**Comment by trevor-scheer** [comment]
Replacing all optional chains is not valid at all and I wouldn't be surprised if it's causing the error. That's critical code for accessing properties in a valid way.

Simplify the reproduction and this error will probably disappear. The first suspicious thing is whatever is going on with ESM at the root of your project.
