### ISSUE TITLE
Federated entity field value is not provided in computed field

### ISSUE THREAD

**Issue by Ryogo-Z** [apollographql/federation#2683]
### Setup
We define 3 services: `Service A`, `Service B`, `Service C` and a gateway.

`Service A` defines simple entity
````
  type ParentItem @key(fields: "id") {
    id: ID!
    name: String!
  }
````
and a query to retrieve a hard-coded list of `ParentItem` entities.

`Service B` define another entity
````
  type ChildItem @key(fields: "id") {
    id: ID!
    name: String!
    parentItem: ParentItem
  }
````
and extends `ParentItem`
````
  type ParentItem @key(fields: "id") {
    id: ID!
    childItems: [ChildItem!]!
  }
````

`Service C` extends `ChildItem` with a calculated field `message`
````
  type ChildItem @key(fields: "id") {
    id: ID!
    name: String! @external
    parentItem: ParentItem @external
    message: String! @requires(fields: "name parentItem { name }")
  }
````

#### Query
Now we try to execute
````
query {
  parentItems {
    childItems {
      message
    }
  }
}
````
#### Expected result
and we expect to receive a response which looks like

<details><summary>valid response</summary>

```javascript
{
  "data": {
    "parentItems": [
      {
        "childItems": [
          {
            "parentItem": {
              "name": "Parent item #1"
            },
            "message": "ParentName: Parent item #1 | ChildName: Child Item #1"
          }
        ]
      },
      {
        "childItems": [
          {
            "parentItem": {
              "name": "Parent item #2"
            },
            "message": "ParentName: Parent item #2 | ChildName: Child Item #2"
          }
        ]
      },
      {
        "childItems": [
          {
            "parentItem": {
              "name": "Parent item #3"
            },
            "message": "ParentName: Parent item #3 | ChildName: Child Item #3"
          }
        ]
      }
    ]
```

</details>

#### Actual result
but instead we'll receive
<details><summary>invalid response</summary>

```javascript
{
  "errors": [
    {
      "message": "Cannot read properties of null (reading 'name')",
      "path": [
        "parentItems",
        0,
        "childItems",
        0,
        "message"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "GraphQLError: Cannot read properties of null (reading 'name')",
          "    at downstreamServiceError (c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:514:16)",
          "    at c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:334:59",
          "    at Array.map (<anonymous>)",
          "    at sendOperation (c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:334:44)",
          "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
          "    at async c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:279:49",
          "    at async executeNode (c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:199:17)",
          "    at async executeNode (c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:190:27)",
          "    at async executeNode (c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:173:40)",
          "    at async c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:96:35"
        ],
        "serviceName": "service_c"
      }
    },
    {
      "message": "Cannot read properties of null (reading 'name')",
      "path": [
        "parentItems",
        1,
        "childItems",
        0,
        "message"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "GraphQLError: Cannot read properties of null (reading 'name')",
          "    at downstreamServiceError (c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:514:16)",
          "    at c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:334:59",
          "    at Array.map (<anonymous>)",
          "    at sendOperation (c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:334:44)",
          "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
          "    at async c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:279:49",
          "    at async executeNode (c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:199:17)",
          "    at async executeNode (c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:190:27)",
          "    at async executeNode (c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:173:40)",
          "    at async c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:96:35"
        ],
        "serviceName": "service_c"
      }
    },
    {
      "message": "Cannot read properties of null (reading 'name')",
      "path": [
        "parentItems",
        2,
        "childItems",
        0,
        "message"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "GraphQLError: Cannot read properties of null (reading 'name')",
          "    at downstreamServiceError (c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:514:16)",
          "    at c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:334:59",
          "    at Array.map (<anonymous>)",
          "    at sendOperation (c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:334:44)",
          "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
          "    at async c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:279:49",
          "    at async executeNode (c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:199:17)",
          "    at async executeNode (c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:190:27)",
          "    at async executeNode (c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:173:40)",
          "    at async c:\\Users\\xxx\\Desktop\\apollo_nested_federation\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:96:35"
        ],
        "serviceName": "service_c"
      }
    }
  ],
  "data": null
}
```

</details>

due to `ChildItem.parentItem` field being set to `undefined` for every returned `ChildItem` entity.

### Workaround
It is possible to receive a valid response executing query
````
query {
  parentItems {
    childItems {
      parentItem {
        name
      }
      message
    }
  }
}
````

### Diagnostics
Although query plans generated for both original and workaround queries are quite similar

<details><summary>original query plan</summary>

```javascript
QueryPlan {
  Sequence {
    Fetch(service: "service_a") {
      {
        parentItems {
          __typename
          id
        }
      }
    },
    Parallel {
      Flatten(path: "parentItems.@") {
        Fetch(service: "service_b") {
          {
            ... on ParentItem {
              __typename
              id
            }
          } =>
          {
            ... on ParentItem {
              childItems {
                __typename
                id
                name
                parentItem {
                  __typename
                  id
                }
              }
            }
          }
        },
      },
      Flatten(path: "parentItems.@.childItems.@.parentItem") {
        Fetch(service: "service_a") {
          {
            ... on ParentItem {
              __typename
              id
            }
          } =>
          {
            ... on ParentItem {
              name
            }
          }
        },
      },
    },
    Flatten(path: "parentItems.@.childItems.@") {
      Fetch(service: "service_c") {
        {
          ... on ChildItem {
            __typename
            name
            parentItem {
              name
            }
            id
          }
        } =>
        {
          ... on ChildItem {
            message
          }
        }
      },
    },
  },
}
```

</details>

<details><summary>workaround query plan</summary>

```javascript
QueryPlan {
  Sequence {
    Fetch(service: "service_a") {
      {
        parentItems {
          __typename
          id
        }
      }
    },
    Flatten(path: "parentItems.@") {
      Fetch(service: "service_b") {
        {
          ... on ParentItem {
            __typename
            id
          }
        } =>
        {
          ... on ParentItem {
            childItems {
              __typename
              id
              parentItem {
                __typename
                id
              }
              name
            }
          }
        }
      },
    },
    Flatten(path: "parentItems.@.childItems.@.parentItem") {
      Fetch(service: "service_a") {
        {
          ... on ParentItem {
            __typename
            id
          }
        } =>
        {
          ... on ParentItem {
            name
          }
        }
      },
    },
    Flatten(path: "parentItems.@.childItems.@") {
      Fetch(service: "service_c") {
        {
          ... on ChildItem {
            __typename
            name
            parentItem {
              name
            }
            id
          }
        } =>
        {
          ... on ChildItem {
            message
          }
        }
      },
    },
  },
}
```

</details>

there is one significant difference which is - original query plan will have a `Parallel` block which will include a fetch to retrieve the `ChildItem.parentItem.name` field.
What happens here is that gateway will try to retrieve both `ChildItem` entity and its nested `parentItem` field in 2 parallel fetches, so when gateway tries to fetch the `parentItem` field enclosing `ChildItem` entity does not exists in response context yet and fetch is basically skipped (see: https://github.com/apollographql/federation/blob/0519eecf68238669cb33869a7062b52c1d277fb4/gateway-js/src/executeQueryPlan.ts#L434)

### Link to Reproduction

https://github.com/Ryogo-Z/apollo_nested_federation

**Comment by clenfest** [comment]
I believe what is going on here is that the condition resolver is tricked into thinking that it's locally satisfiable when in fact it will require another subgraph jump because of the `@external` on the ParentItem's `name` field within subgraph C. 

See comments in `canSatisfyConditions`

https://github.com/apollographql/federation/blob/main/query-graphs-js/src/graphPath.ts#L1748-L1758

Seems like a real issue and I'll continue looking at it.

**Comment by harshitkumar31** [comment]
Here's another query which fails with the same error
```
query {
  parentItems {
    childItems {
      ParentItem: parentItem {
        name
        id
      }
      message
    }
  }
}
```



`@apollo/gateway` seems to get confused when the alias matches the typename and skips the subgraph jump.



<details>
  <summary>Error</summary>
  

```js
  {
  "data": {},
  "errors": [
    {
      "message": "Cannot read properties of null (reading 'name')",
      "path": [
        "parentItems",
        0,
        "childItems",
        0,
        "message"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "GraphQLError: Cannot read properties of null (reading 'name')",
          "    at downstreamServiceError (/Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:514:16)",
          "    at /Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:334:59",
          "    at Array.map (<anonymous>)",
          "    at sendOperation (/Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:334:44)",
          "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
          "    at async /Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:279:49",
          "    at async executeNode (/Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:199:17)",
          "    at async executeNode (/Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:190:27)",
          "    at async executeNode (/Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:173:40)",
          "    at async /Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:96:35"
        ],
        "serviceName": "service_c"
      }
    },
    {
      "message": "Cannot read properties of null (reading 'name')",
      "path": [
        "parentItems",
        1,
        "childItems",
        0,
        "message"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "GraphQLError: Cannot read properties of null (reading 'name')",
          "    at downstreamServiceError (/Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:514:16)",
          "    at /Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:334:59",
          "    at Array.map (<anonymous>)",
          "    at sendOperation (/Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:334:44)",
          "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
          "    at async /Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:279:49",
          "    at async executeNode (/Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:199:17)",
          "    at async executeNode (/Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:190:27)",
          "    at async executeNode (/Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:173:40)",
          "    at async /Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:96:35"
        ],
        "serviceName": "service_c"
      }
    },
    {
      "message": "Cannot read properties of null (reading 'name')",
      "path": [
        "parentItems",
        2,
        "childItems",
        0,
        "message"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "GraphQLError: Cannot read properties of null (reading 'name')",
          "    at downstreamServiceError (/Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:514:16)",
          "    at /Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:334:59",
          "    at Array.map (<anonymous>)",
          "    at sendOperation (/Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:334:44)",
          "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
          "    at async /Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:279:49",
          "    at async executeNode (/Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:199:17)",
          "    at async executeNode (/Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:190:27)",
          "    at async executeNode (/Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:173:40)",
          "    at async /Users/h0k00rz/Projects/Github/apollo_nested_federation/node_modules/@apollo/gateway/dist/executeQueryPlan.js:96:35"
        ],
        "serviceName": "service_c"
      }
    }
  ]
}
```
 </details>

The same query works fine with `@apollo/gateway@0.x`

**Comment by pcmanus** [comment]
Thanks for the report and the clear reproduction. The problem was indeed that in the plan of the faulty query, the 2nd fetch to `service_a` was in parallel of the one to `service_b`, even though that `service_a` fetch relied on the result of the `service_b` fetch, so those have to be sequential instead. The underlying reason being due to the fact that the code for `@requires` sometimes genuinely have to ensure it "removes" some unnecessary dependencies between fetches to generate optimal plans, but that check was buggy and was in this case removing a dependency it shouldn't have.

I've pushed #2726 which fixes this. I took the liberty to "stole" your reproduction example as a unit test, hope you don't mind.

**Comment by Ryogo-Z** [comment]
@pcmanus thank you. Tbh, I tried to fix it myself before raising an issue, I traced it down to [buildPlan.ts#L4244](https://github.com/apollographql/federation/blob/e963de112d2096aa936e2b2f28f7e37b0c4e004c/query-planner-js/src/buildPlan.ts#L4244), but did not have time to pursue it further.
Glad to hear I was on a right track at least :)
