### ISSUE TITLE
Fragments normalizer error: "Cannot normalize x at Y which does not have that field"

### ISSUE THREAD

**Issue by id-ilych** [apollographql/federation#2721]
### Issue Description

Hello, it seems that fragment normalizer has an issue when there are interfaces used and implemented in multiple services.

<details>
<summary>Considering the schemas in the linked reproduction sandbox.</summary>
<br />

Products service:
```graphql
type Query {
  products: [Product]
}

type Link {
  url: String!
}

interface WebResource {
  webResource: Link!
}

type Product implements WebResource @key(fields: "id") {
  id: String!
  name: String
  webResource: Link!
}
```

Reviews service:
```graphql
type Query {
  reviews: [Review]
  mostReviewedProduct: Product
}

type Link {
  url: String!
}

interface WebResource {
  webResource: Link!
}

type Review implements WebResource {
  id: String!
  content: String
  webResource: Link!
}

extend type Product @key(fields: "id") {
  id: String! @external
  reviews: [Review]
}
```

</details>

This query works just fine
```graphql
query QueryThatWorks {
  mostReviewedProduct {
    webResource { url }
    reviews { webResource { url } }
  }
}
```

But this equivalent but refactored one doesn't work:
```graphql
query QueryThatDoesntWork {
  mostReviewedProduct { ...ProductFragment }
}

fragment ProductFragment on Product {
  webResource { url }
  reviews { ...WebResourceFragment }
}

fragment WebResourceFragment on WebResource {
  webResource { url }
}
```
Error
```json
{
  "data": {},
  "errors": [
    {
      "message": "Cannot normalize webResource at Product which does not have that field",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "Error: Cannot normalize webResource at Product which does not have that field",
          "    at assert (/project/sandbox/node_modules/@apollo/federation-internals/src/utils.ts:12:11)",
          "    at FieldSelection.normalize (/project/sandbox/node_modules/@apollo/federation-internals/src/operations.ts:3047:11)",
          "    at lazyMap.parentType.parentType (/project/sandbox/node_modules/@apollo/federation-internals/src/operations.ts:1731:50)",
          "    at SelectionSet.lazyMap (/project/sandbox/node_modules/@apollo/federation-internals/src/operations.ts:1752:23)",
          "    at SelectionSet.normalize (/project/sandbox/node_modules/@apollo/federation-internals/src/operations.ts:1731:17)",
          "    at InlineFragmentSelection.normalizeKnowingItIntersects (/project/sandbox/node_modules/@apollo/federation-internals/src/operations.ts:3362:46)",
          "    at InlineFragmentSelection.normalize (/project/sandbox/node_modules/@apollo/federation-internals/src/operations.ts:3166:17)",
          "    at lazyMap.parentType.parentType (/project/sandbox/node_modules/@apollo/federation-internals/src/operations.ts:1731:50)",
          "    at SelectionSet.lazyMap (/project/sandbox/node_modules/@apollo/federation-internals/src/operations.ts:1752:23)",
          "    at SelectionSet.normalize (/project/sandbox/node_modules/@apollo/federation-internals/src/operations.ts:1731:17)"
        ]
      }
    }
  ]
}
```

The issue seems to come from the fact that given interface is implemented for the type in question by different service so the normalizer is confused to thing that the type does not implement it at all.

### Link to Reproduction

https://codesandbox.io/p/sandbox/mystifying-greider-fwpy8w

### Reproduction Steps

* Execute `QueryThatWorks` and it works
* Execute equivalent but refactored `QueryThatDoesntWork` and it doesn't work (the error is in the description

**Comment by pcmanus** [comment]
Thank your for the clear reproduction. Created #2725 to fix this. This is indeed related to the fact that `WebResource` exists in the "Reviews" service, but `Product` does not implement it (while it does in the supergraph). Which is fine btw, just some fragment code was not handling this correctly.

**Comment by id-ilych** [comment]
Hey @pcmanus :wave:

Thank you :) Could you also check https://github.com/apollographql/federation/pull/2716?
