### ISSUE TITLE
2.5.6 -> 2.5.7 introduces breaking change

### ISSUE THREAD

**Issue by cdavaz** [apollographql/federation#3183]
Moving from 2.5.6 to [2.5.7](https://github.com/apollographql/federation/blob/main/gateway-js/CHANGELOG.md#patch-changes-27) introduces a breaking change. Server starts up fine however when we go to execute any query we now get the following stack trace:

```
TypeError: Cannot read properties of undefined (reading 'kind'),
  at isListType (/project/node_modules/@apollo/query-planner/node_modules/@apollo/federation-internals/dist/definitions.js:56:17),
  at GroupPath.updatedResponsePath (/project/node_modules/@apollo/query-planner/dist/buildPlan.js:1001:55),
  at GroupPath.add (/project/node_modules/@apollo/query-planner/dist/buildPlan.js:1009:100),
  at computeGroupsForTree (/project/node_modules/@apollo/query-planner/dist/buildPlan.js:2336:53),
  at computeRootFetchGroups (/project/node_modules/@apollo/query-planner/dist/buildPlan.js:2138:9),
  at QueryPlanningTraversal.updatedDependencyGraph (/project/node_modules/@apollo/query-planner/dist/buildPlan.js:356:15),
  at QueryPlanningTraversal.computeBestPlanFromClosedBranches (/project/node_modules/@apollo/query-planner/dist/buildPlan.js:312:43),
  at QueryPlanningTraversal.findBestPlan (/project/node_modules/@apollo/query-planner/dist/buildPlan.js:135:14),
  at computeRootParallelBestPlan (/project/node_modules/@apollo/query-planner/dist/buildPlan.js:1958:36),
  at computeRootParallelDependencyGraph (/project/node_modules/@apollo/query-planner/dist/buildPlan.js:1954:12)
```

The compiled Javascript reference at the top of the stack trace is:

```javascript
function isListType(type) {
    return type.kind == 'ListType';
}
```

I would not expect a minor version change to introduce such an issue. This is unfortunately preventing us from upgrading to the latest version of gateway, which still triggers this exception.

**Comment by cdavaz** [comment]
Updating the rest of the Apollo libraries seemed to fix this issue, closing.
