### ISSUE TITLE
Getting Exception "Object required to be not null" while calling graphql endpoint from federation

### ISSUE THREAD

**Issue by AmanMehndiratta** [apollographql/federation#613]
I am using springboot version 2.4.4 and Java 1.8.0_281

Dependency used:

`<dependency>
    <groupId>com.graphql-java</groupId>
    <artifactId>graphql-spring-boot-starter</artifactId>
    <version>5.0.2</version>
</dependency>`
`<dependency>
    <groupId>com.apollographql.federation</groupId>
    <artifactId>federation-graphql-java-support</artifactId>
    <version>0.3.2</version>
</dependency>`
`<dependency>
    <groupId>com.graphql-java</groupId>
    <artifactId>graphql-java</artifactId>
    <version>13.0</version>
</dependency>`
`<dependency>
    <groupId>com.graphql-java</groupId>
    <artifactId>graphql-java-tools</artifactId>
    <version>5.2.4</version>
</dependency>`

Configuration for making springboot service schema ready:

`@Configuration
public class GraphQLConfig {
	
	@Bean
	public GraphQLSchema customSchema(SchemaParser schemaParser) {

		GraphQLSchema schema = GraphQLSchema
				.newSchema(schemaParser.makeExecutableSchema()).clearAdditionalTypes().build();

		return Federation.transform(schema).build();

	}
}`

Schema created:

`type Query{
    response: Response!

}

type Response{
    id: Int!
    response: String
}

`

Resolver:
`@Service
public class ResponseResolver implements GraphQLQueryResolver {

    @Autowired
    private ResponseService responseService;

    public Response getResponse(){
       return responseService.getResponse();
    }
}
`

On running apollo federation service, getting this exception:
`
graphql.AssertException: Object required to be not null
	at graphql.Assert.assertNotNull(Assert.java:29) ~[graphql-java-13.0.jar:na]
	at graphql.ExecutionInput$Builder.cacheControl(ExecutionInput.java:232) ~[graphql-java-13.0.jar:na]
	at graphql.ExecutionInput.transform(ExecutionInput.java:115) ~[graphql-java-13.0.jar:na]
	at graphql.GraphQL.ensureInputHasId(GraphQL.java:522) ~[graphql-java-13.0.jar:na]
	at graphql.GraphQL.executeAsync(GraphQL.java:490) ~[graphql-java-13.0.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:432) ~[graphql-java-13.0.jar:na]
	at graphql.servlet.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:92) ~[graphql-java-servlet-6.1.2.jar:na]
	at graphql.servlet.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:88) ~[graphql-java-servlet-6.1.2.jar:na]
	at graphql.servlet.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:39) ~[graphql-java-servlet-6.1.2.jar:na]
	at graphql.servlet.AbstractGraphQLHttpServlet.query(AbstractGraphQLHttpServlet.java:265) ~[graphql-java-servlet-6.1.2.jar:na]
	at graphql.servlet.AbstractGraphQLHttpServlet.lambda$new$2(AbstractGraphQLHttpServlet.java:183) ~[graphql-java-servlet-6.1.2.jar:na]
	at graphql.servlet.AbstractGraphQLHttpServlet.doRequest(AbstractGraphQLHttpServlet.java:236) ~[graphql-java-servlet-6.1.2.jar:na]
	at graphql.servlet.AbstractGraphQLHttpServlet.doRequestAsync(AbstractGraphQLHttpServlet.java:227) ~[graphql-java-servlet-6.1.2.jar:na]
	at graphql.servlet.AbstractGraphQLHttpServlet.doPost(AbstractGraphQLHttpServlet.java:257) ~[graphql-java-servlet-6.1.2.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) ~[tomcat-embed-core-9.0.44.jar:4.0.FR]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.44.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.44.jar:9.0.44]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-5.3.5.jar:5.3.5]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.5.jar:5.3.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.5.jar:5.3.5]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.5.jar:5.3.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.5.jar:5.3.5]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.5.jar:5.3.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.5.jar:5.3.5]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.5.jar:5.3.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_281]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_281]`

**Comment by sachindshinde** [comment]
@AmanMehndiratta
This is a bug with `graphql-java` v13.0.

Specifically in [`ExecutionInput`](https://github.com/graphql-java/graphql-java/blob/v13.0/src/main/java/graphql/ExecutionInput.java#L29), the class offers a public constructor that sets `cacheControl` to null. This makes `ExecutionInput` objects created in such a manner not work with [`ExecutionInput#transform()`](https://github.com/graphql-java/graphql-java/blob/v13.0/src/main/java/graphql/ExecutionInput.java#L108), which tries to copy the properties of the given `ExecutionInput` using [`ExecutionInput.Builder`](https://github.com/graphql-java/graphql-java/blob/v13.0/src/main/java/graphql/ExecutionInput.java#L155) (and the builder [will throw when setting `cacheControl` to null](https://github.com/graphql-java/graphql-java/blob/v13.0/src/main/java/graphql/ExecutionInput.java#L232)).

This public constructor is particularly in use by `graphql-java-servlet` v6.1.2 in [GraphQLInvocationInput#createExecutionInput()](https://github.com/graphql-java-kickstart/graphql-java-servlet/blob/v6.1.2/src/main/java/graphql/servlet/GraphQLInvocationInput.java). This `ExecutionInput` object is passed to `ExecutionInput#transform()` in [GraphQL#ensureInputHasId()](https://github.com/graphql-java/graphql-java/blob/v13.0/src/main/java/graphql/GraphQL.java#L522).

This has been fixed in `graphql-java` v14.0, which [removes that public constructor](https://github.com/graphql-java/graphql-java/blob/v14.0/src/main/java/graphql/ExecutionInput.java). You can alternatively upgrade `graphql-java-servlet` to version v7.0.0, which [switches to using the builder instead of the public constructor](https://github.com/graphql-java-kickstart/graphql-java-servlet/blob/v7.0.0/src/main/java/graphql/servlet/GraphQLInvocationInput.java#L43) (v7.0.0 claims to support `graphql-java` v10 and above, so you wouldn't have to switch away from `graphql-java` v13.0 if that's a requirement).

If neither of these upgrades fixes the issue, let us know and we can reopen the issue!

**Comment by AmanMehndiratta** [comment]
Hi @sachindshinde 

We are still facing the issue. As you have mentioned, we have updated the version of Graphql-Java and graphql-java-servlet both. But still issue is coming. 

**Versions used:** 
`<dependency>
			<groupId>com.graphql-java</groupId>
			<artifactId>graphql-java</artifactId>
			<version>14.0</version>
		</dependency>`

`<dependency>
			<groupId>com.graphql-java-kickstart</groupId>
			<artifactId>graphql-java-servlet</artifactId>
			<version>7.0.0</version>
		</dependency>`



**Issue coming:**


`***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.apollographql.federation.graphqljava.SchemaTransformer.sdl(SchemaTransformer.java:141)

The following method did not exist:

    graphql.schema.idl.SchemaPrinter$Options.includeSchemaDefintion(Z)Lgraphql/schema/idl/SchemaPrinter$Options;

The method's class, graphql.schema.idl.SchemaPrinter$Options, is available from the following locations:

    jar:file:/C:/Users/amamehnd/.m2/repository/com/graphql-java/graphql-java/14.0/graphql-java-14.0.jar!/graphql/schema/idl/SchemaPrinter$Options.class

The class hierarchy was loaded from the following locations:

    graphql.schema.idl.SchemaPrinter.Options: file:/C:/Users/amamehnd/.m2/repository/com/graphql-java/graphql-java/14.0/graphql-java-14.0.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of graphql.schema.idl.SchemaPrinter$Options
`

**Comment by AmanMehndiratta** [comment]
@sachindshinde  Can you please reopen this issue?

**Comment by sachindshinde** [comment]
@AmanMehndiratta 
I believe the issue here is that there are breaking changes in the `graphql-java` API between v13.0 and v14.0, which explains why `federation-graphql-java-support` v0.3.2 is failing when trying to use the `graphql-java` API (it was developed around v13.0, but the methods no longer exist in v14.0). Can you try upgrading the `federation-graphql-java-support` artifact from v0.3.2 to v0.4.3?
